### ISSUE TITLE
Doesn't respect new lines at EOF

### ISSUE THREAD

**Issue by okonet** [jlongster/prettier#55] opened 2017-01-10 20:02 UTC
Not sure if it's "by design" but it strips the new lines at end of files.

<img width="269" alt="2017-01-10 at 20 48" src="https://cloud.githubusercontent.com/assets/11071/21822104/3cd228a6-d776-11e6-88eb-a0aefd951192.png">

**Comment by jlongster** [comment] 2017-01-11 05:13
It should respect those. It did for some files at least. This should be fixed.

**Comment by oviava** [comment] 2017-01-11 12:32
Confirming this as well - my usecase specifically is on `export default moduleName;`- removes semicolon and new line

**Closed** 2017-01-11 15:15 UTC

**Comment by sapegin** [comment] 2017-05-14 07:32
@jlongster What’s the current design? Should it *respect* or always add them? I’m trying to automate code formatting in Markdown examples using [textlint-rule-eslint](https://github.com/azu/textlint-rule-eslint) and [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and it keeps adding new line after each example. Not sure where to better fix that ;-/

**Comment by lydell** [comment] 2017-05-14 09:38
Prettier makes sure that files end with a single newline by design.

**Comment by RomiC** [comment] 2017-09-20 11:36
@lydell why not do it as an option? While there is an `eol-last` rule in eslint I think it's good idea to have the similar option for prettier, not to format file twice.
