### ISSUE TITLE
Allow newline after block styles comment.

### ISSUE THREAD

**Issue by Aaron-Pool** [jlongster/prettier#356] opened 2017-01-20 22:34 UTC
I try to break up my code with pretty, block style comment headers to make the sections more easily identifiable. Prettier keeps smashing the below each header right into the bottom border of it. Makes me feel claustrophobic.

Example: 
```js
    /****************************************
     *           Unimplemented Functions     *
     ****************************************/
    function getStuff() {
        throw 'Error: getStuff has not been implemented!';
    }

    function getOtherStuff() {
        throw 'Error: getOtherStuff has not been implemented!';
    }
```

Whereas I would prefer it be nice and breathable, like this:
```js
    /****************************************
     *           Unimplemented Functions     *
     ****************************************/
    
    function getStuff() {
        throw 'Error: getStuff has not been implemented!';
    }

    function getOtherStuff() {
        throw 'Error: getOtherStuff has not been implemented!';
    }
```

It seems like the general "prettier" trend is to allow a single newline after block code elements, any reason this newline is removed?

**Comment by vjeux** [comment] 2017-01-20 22:50
This is a bug with our current implementation. The intended behavior of `prettier` is to preserve empty lines as they were in the original file. @jlongster is fixing a lot of bugs with comments right now, so hopefully this won't be an issue soon!

**Comment by vjeux** [comment] 2017-01-27 02:53
This is fixed on master :)

**Comment by vjeux** [comment] 2017-01-27 02:59
Actually, this is not fixed. It worked because we have a special case for the first comment of the file.

**Closed** 2017-01-27 19:05 UTC
Labels: bug, Comments
