### ISSUE TITLE
Nested function wrappers indentation issue

### ISSUE THREAD

**Issue by sonaye** [jlongster/prettier#513] opened 2017-01-29 17:55 UTC
version: 0.13.1

formatting issue:
![screen shot 2017-01-29 at 8 49 48 pm](https://cloud.githubusercontent.com/assets/23000873/22406489/03c5650c-e665-11e6-8677-32fc7dee2d7b.png)

how it should look like:
![screen shot 2017-01-29 at 8 51 43 pm](https://cloud.githubusercontent.com/assets/23000873/22406492/0bd7968e-e665-11e6-95de-3f10758e7238.png)

**Comment by vjeux** [comment] 2017-01-29 20:55
Thanks for the bug report, here's a text version and live browser to reproduce:

```js
const Settings = actionSheet(
  inject('globalsStore', 'userStore')(observer(props => {
    const shareSheet = () => {
      // production: write a share template
      Share.share({
        title: 'A title to go with the shared url ..',
        message: 'A message to go with the shared url ..',
        url: 'https://null'
      });
    };
  }))
);
```

outputs

```js
const Settings = actionSheet(
  inject("globalsStore", "userStore")(observer(props => {
      const shareSheet = () => {
        // production: write a share template
        Share.share({
          title: "A title to go with the shared url ..",
          message: "A message to go with the shared url ..",
          url: "https://null"
        });
      };
    }))
);
```

If I understand correctly, the issue is that it is indented by 4 spaces but should only be indented two spaces?

**Comment by vjeux** [comment] 2017-01-29 21:01
Minimal repro case:

```js
f(g(() => {
  a
}))
```

outputs

```js
f(g(() => {
    a;
  }));
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22f(g(()%20%3D%3E%20%7B%5Cn%20%20a%5Cn%7D))%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Atrue%7D%7D

If you add a h() in the mix it indents by three * 2 spaces.

**Comment by sonaye** [comment] 2017-01-29 21:45
true, your understanding is correct, everything inside would have extra two spaces, including the render method in react. I think it would be better if there was a support for such a case.

+ thanks for the great work, oh boy 1.0.0 would be glorious! i can't even imagine.

**Comment by vjeux** [comment] 2017-01-29 22:56
> oh boy 1.0.0 would be glorious!

Soon, please keep sending feedback on what isn't printed correctly, we want to fix everything!

**Comment by vjeux** [comment] 2017-01-29 23:28
Okay, here's a fix for it: #517. It prints it the way you wanted it.

```js
const Settings = actionSheet(
  inject("globalsStore", "userStore")(
    observer(props => {
      const shareSheet = () => {
        // production: write a share template
        Share.share({
          title: "A title to go with the shared url ..",
          message: "A message to go with the shared url ..",
          url: "https://null"
        });
      };
    })
  )
);
```

**Comment by sonaye** [comment] 2017-01-29 23:39
I appreciate the quick response, will defiantly keep you updated with any issues i find, this is a great tool and I do want to see it perfected.

Since i started using prettier i've been adding eslint ignore rules that were broken by formatting, I chose to just ignore those errors and go with prettier formatting blindly, I will check the list and see if anything is worthy of enhancing.

**Comment by sonaye** [comment] 2017-01-29 23:41
they are mainly react/jsx related.

**Comment by vjeux** [comment] 2017-01-29 23:50
If you can report which rules are broken with examples that would be helpful!

**Comment by sonaye** [comment] 2017-01-30 00:09
### example 1
```
error  Expected indentation of 14 space characters but found 16                                           react/jsx-indent
error  Expected indentation of 22 space characters but found 24                                           react/jsx-indent-props
error  The closing bracket must be aligned with the line containing the opening tag (expected column 21)  react/jsx-closing-bracket-location
```
![screen shot 2017-01-30 at 2 50 54 am](https://cloud.githubusercontent.com/assets/23000873/22409309/edd6b992-e698-11e6-97c4-d33f4c501954.png)

### example 2
```
error  Expected indentation of 16 space characters but found 18                                           react/jsx-indent-props
error  The closing bracket must be aligned with the line containing the opening tag (expected column 15)  react/jsx-closing-bracket-location
```
![screen shot 2017-01-30 at 3 02 13 am](https://cloud.githubusercontent.com/assets/23000873/22409318/249f461a-e699-11e6-849f-d1584c04a630.png)

**Comment by sonaye** [comment] 2017-01-30 00:11
![screen shot 2017-01-30 at 3 08 12 am](https://cloud.githubusercontent.com/assets/23000873/22409350/852a45e8-e699-11e6-9e64-dab71de17111.png)
![screen shot 2017-01-30 at 3 08 24 am](https://cloud.githubusercontent.com/assets/23000873/22409351/853085de-e699-11e6-9102-d6355214d0b6.png)
![screen shot 2017-01-30 at 3 08 36 am](https://cloud.githubusercontent.com/assets/23000873/22409352/85352ff8-e699-11e6-9d7a-5037b0f18f34.png)
![screen shot 2017-01-30 at 3 08 47 am](https://cloud.githubusercontent.com/assets/23000873/22409353/853bc2f0-e699-11e6-9435-5366fbaca854.png)

Pretty much all the errors are related to these couple of rules, not sure if they are worthy of investigating. Are you guys interested an covering some of the rules from https://github.com/airbnb/javascript/tree/master/react?

**Comment by vjeux** [comment] 2017-01-30 00:50
It seems like the lint rule doesn't like that ?: indents things. We should figure out if we want prettier to output things differently for it.

For the closing bracket, we probably want to put it where the rule tells us to. I'll see how hard it is to.

**Comment by vjeux** [comment] 2017-01-30 03:04
https://github.com/jlongster/prettier/pull/518 implements putting the bracket at the right place.

**Comment by lydell** [comment] 2017-01-30 06:56
Somewhat related: There's also [eslint-config-prettier](http://github.com/lydell/eslint-config-prettier) for turning all rules that are unnecessary or conflict with prettier off.

**Closed** 2017-01-31 16:45 UTC
Labels: bug

**Comment by marharyta** [comment] 2018-06-27 12:16
Hello! Is there any specific fix for that?
I am having exactly the same problem here.
My config is:
package.json
```
"eslint": "^4.19.1",
"eslint-config-prettier": "^2.9.0",
"eslint-loader": "^2.0.0",
"eslint-plugin-prettier": "^2.6.0",
"eslint-plugin-react": "^7.10.0",
"prettier": "^1.12.1",

```

.eslintrc

```
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true
  },
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'prettier',
    'plugin:prettier/recommended'
  ],
  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true
    },
    sourceType: 'module'
  },
  plugins: ['react', 'prettier'],
  rules: {
    indent: ['error', 2, { SwitchCase: 1 }],
    'linebreak-style': ['error', 'unix'],
    quotes: ['warn', 'single'],
    semi: ['error', 'always'],
    'prettier/prettier': 'error',
    indentSwitchCase: true
  }
};

```

prettier config
```
// .prettierrc.js
module.exports = {
  printWidth: 80,
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  bracketSpacing: true
};
```

**Comment by j-f1** [comment] 2018-06-27 13:16
@marharyta Can you open a new issue and fill out the bug report template please?
