### ISSUE TITLE
Prettier break code with expression as the property name

### ISSUE THREAD

**Issue by onemen** [jlongster/prettier#94] opened 2017-01-11 08:24 UTC
Prettier break code with expression as the property name
Before:
```
let testObj = {
  toggleEventListener(enable) {
    let eventListener = enable ? "addEventListener" : "removeEventListener";
    document.getElementById("foo")[eventListener]("dblclick", this.blockDblclick, false);
  },
  blockDblclick(event) {
    event.preventDefault();
  },
};
```
After:
```
let testObj = {
  toggleEventListener(enable) {
    let eventListener = enable ? "addEventListener" : "removeEventListener";

    document
      .getElementById("foo")
      .eventListener("dblclick", this.blockDblclick, false);
  },
  blockDblclick(event) {
    event.preventDefault();
  }
};
```

It should use document.getElementById("foo")[eventListener],
not document.getElementById("foo").eventListener

**Comment by vramana** [comment] 2017-01-11 08:56
This is most likely a duplicate of #23

**Closed** 2017-01-11 18:27 UTC
Labels: duplicate
