### ISSUE TITLE
JSX spaces

### ISSUE THREAD

**Issue by daltones** [jlongster/prettier#32] opened 2017-01-10 17:10 UTC
In Prettier's live demo there's this:
```jsx
<div>
  hello ${name}! JSX is <strong>supported</strong>
</div>
```

And it's formatted as:
```jsx
<div>
  hello ${name}! JSX is<strong>supported</strong>
</div>
```

We can see that spaces around tags [and regular JS expressions] in the same line are missing.

You can also reproduce the issue this way:
```jsx
<div>
  text {name} more text and <em>tag</em> and text
</div>
```

Formatted as:
```jsx
<div>
  text{name}more text and<em>tag</em>and text
</div>
```

**Comment by jlongster** [comment] 2017-01-10 17:10
Dupe of https://github.com/jlongster/prettier/issues/30, thanks!

**Closed by jlongster** 2017-01-10 17:10 UTC

**Comment by daltones** [comment] 2017-01-10 17:12
Wow, that was fast lol

Thanks for the new tool! 😃
