### ISSUE TITLE
Disabling Semicolons

### ISSUE THREAD

**Issue by hnordt** [jlongster/prettier#192] opened 2017-01-14 13:53 UTC
Thank you for this awesome project!

Would be great to have an option to disable semicolons.

**Comment by demoneaux** [comment] 2017-01-14 14:30
This is a duplicate of #12. Support for disabling semicolons would not be actively developed, but if a reasonably succinct implementation can be done, it might be added to this project. For now you can use something like https://github.com/kentcdodds/prettier-eslint to remove semicolons via `eslint --fix`.

**Closed** 2017-01-14 15:22 UTC
