### ISSUE TITLE
Please add a way to format sources without semicolons

### ISSUE THREAD

**Issue by alphara** [jlongster/prettier#264] opened 2017-01-17 07:01 UTC
Semicolons are excess in JavaScipt sources

**Comment by JustFly1984** [comment] 2017-01-17 07:06
I agree that semicolons should be optional. Your tool is very nice, but currently we can't use it cos our style guides forbid semicolons.
Your tool adds to much stuff, and it is hard to diff commits, after your tool ads semicolons everywhere.

**Comment by viktorbezdek** [comment] 2017-01-17 08:55
+1

Optional semicolons are a must for me. Your tool formats code really nicely otherwise.

**Comment by demoneaux** [comment] 2017-01-17 09:10
This issue is a duplicate of #12. We won't be actively working on this feature, but if someone came up with a reasonable prototype/solution, we might work on adding this into Prettier.

**Comment by jlongster** [comment] 2017-01-17 16:25
Yes, please see the resolution at #12. You can freely code without semicolons but we will add them for consistently. It's not a simple matter of removing them because there are cases where we need to specially detect when to add them and it makes formatting harder.

This is an opinion that for now we are not going to change, much like `standard` will never have the option to add semicolons. Really, in the end, it doesn't matter at all and the fact that prettier will add them for you removes any annoyances you have in writing them.

**Closed by jlongster** 2017-01-17 16:25 UTC

**Comment by tony-kerz** [comment] 2017-01-22 17:05
for me it's not as much about writing the semicolons as reading them, but i'm one of those guys that liked coffeescript too, so take that fwiw ;)
