### ISSUE TITLE
jsx conditions formatted strange with printWidth > 2

### ISSUE THREAD

**Issue by smacker** [jlongster/prettier#564] opened 2017-02-02 07:15 UTC
With printWidth=2 everything works great, but we use printWidth=4 and some jsx looks very weird.

Input:
```js
function test() {
  return <div>{ a ? <a with-long-attributes="long-value-to-break" and-one-more="test"/> : null }</div>;
}
```

Output:
```js
function test() {
    return (
        <div>
            {a
                ? <a
                        with-long-attributes="long-value-to-break"
                        and-one-more="test"
                    />
                : null}
        </div>
    );
}
```

Expected:
```js
function test() {
    return (
        <div>
            {a
                ? <a
                      with-long-attributes="long-value-to-break"
                      and-one-more="test"
                  />
                : null}
        </div>
    );
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20test()%20%7B%5Cn%20%20return%20%3Cdiv%3E%7B%20a%20%3F%20%3Ca%20with-long-attributes%3D%5C%22long-value-to-break%5C%22%20and-one-more%3D%5C%22test%5C%22%2F%3E%20%3A%20null%20%7D%3C%2Fdiv%3E%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A60%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment] 2017-02-02 16:08
cc @rattrayalex 

I think this is working as intended, but would like to get your input.

**Comment by rattrayalex** [comment] 2017-02-02 16:53
Ah, I see, there's an extra indent. Yeah, this is a bug

**Comment by rattrayalex** [comment] 2017-02-02 18:35
(to be clear, assuming you meant `tabWidth` not `printWidth`)

**Comment by vjeux** [comment] 2017-02-02 19:08
Was fixed by #577

**Closed by vjeux** 2017-02-02 19:08 UTC
Labels: bug

**Comment by rhengles** [comment] 2017-02-02 19:54
So I guess this is what @jlongster meant when he said "tabs make this whole project pretty hard" 😃 

Well, I had to add a new primitive "align-spaces" for this purpose, and when using tabs I will use always one tab (as was done before).

**Comment by smacker** [comment] 2017-02-03 04:00
Tried master branch on my project. JSX now looks awesome! Thanks guys!
