### ISSUE TITLE
Blank line in between each import?

### ISSUE THREAD

**Issue by ryancole** [jlongster/prettier#214] opened 2017-01-15 03:52 UTC
I've not seen projects that put blank lines in between each `import` statement, before. Is this a common formatting pattern? Seems like it'd eat up a ton of vertical space pretty quickly.

![untitled](https://cloud.githubusercontent.com/assets/484801/21960111/af0f7b6e-daa3-11e6-9cb5-8d5b83eefe2c.png)

**Comment by demoneaux** [comment] 2017-01-15 04:03
You seem to be using Windows. There was a bug with Windows' CRLF (#151), where additional newlines similar to what you are encountering are added between statements. This has since been fixed. Perhaps you could update your prettier-atom extension.

**Comment by ryancole** [comment] 2017-01-15 04:07
@demoneaux Yup, indeed on Windows 10. I'm using the latest offered atom plugin. It's not offering any update. It's prettier-atom v0.0.6 on atom v1.13.0 ia32.

**Comment by demoneaux** [comment] 2017-01-15 04:22
Oh, this was just fixed yesterday and released in prettier 0.0.7, which has not been released in prettier-atom yet. Maybe you could wait for a while longer for the next release :)

**Comment by ryancole** [comment] 2017-01-15 04:23
no worries!

**Comment by vjeux** [comment] 2017-01-15 05:25
@jlongster published a new version 12 minutes ago. Can you try again? :)

![image](https://cloud.githubusercontent.com/assets/197597/21960423/08029142-daa0-11e6-9528-075df94b8253.png)

**Comment by ryancole** [comment] 2017-01-15 05:33
Just updated. Honestly I'm not sure what it's *supposed* to do with respect to new lines.

After updating, it now will leave a new line in between lines if I have one, and it also will not force a new line in between lines if I don't have one. Lastly, it removes excessive new lines down to just 1 blank line in between lines. This feels "correct" as it's flexible and respects my new lines if I want them.

Prior to updating, it'd force a new line in between imports, which it no longer appears to do! 👍

**Comment by vjeux** [comment] 2017-01-15 05:36
The intended behavior is as you described. It maintains new lines however they were before except that it reduces them to at most one empty line. If that's not the way you want it to be, please let me know, otherwise I'm going to close this as the bug is fixed :)

**Comment by ryancole** [comment] 2017-01-15 05:36
Yup that's good! Thanks.

**Closed by vjeux** 2017-01-15 05:36 UTC
Labels: bug
