### ISSUE TITLE
removes semi colon after `export default`

### ISSUE THREAD

**Issue by theverything** [jlongster/prettier#60] opened 2017-01-10 20:15 UTC
before
``` javascript
function thing(arg) {
  return arg;
}

export default thing;
```

after
``` javascript
function thing(arg) {
  return arg;
}

export default thing // <-- missing semi colon
```

**Comment by bakkot** [comment] 2017-01-10 20:18
Duplicate of #22

**Comment by theverything** [comment] 2017-01-10 20:21
oops didn't see it on the next page. closing.

**Closed** 2017-01-10 20:21 UTC
