### ISSUE TITLE
Sublime Text Plugin

### ISSUE THREAD

**Issue by OrkoHunter** [jlongster/prettier#17] opened 2017-01-10 16:29 UTC
Does prettier have any sublime text plugin? The README only mentions Atom and emacs.

**Comment by jlongster** [comment] 2017-01-10 17:22
Not yet! Someone else needs to build :) A PR would be great (even if it's just a link to another package)

**Comment by OrkoHunter** [comment] 2017-01-10 17:28
I feel the library is trending too fast for me to get inspired and learn how to write Sublime Text plugins ;)

**Comment by Haroenv** [comment] 2017-01-10 18:24
You can however put it as a *build system* in sublime text, where it's just the cli command with the current file as argument (and with `--write`)

**Comment by jlangston** [comment] 2017-01-10 21:19
Prettier seems great. I've been using a different sublime text plugin but it stopped working some time ago but it was pretty easy to swap out the node formatting package to use prettier. This is very much a WIP if your interested https://github.com/jlangston/sublime-jsprettier

**Comment by danreeves** [comment] 2017-01-10 21:22
@jlangston hah, you beat me to it. Here's my WIP: https://github.com/danreeves/sublime-prettier

**Comment by jlangston** [comment] 2017-01-10 23:22
@danreeves nice work! I figured a few might pop up around this. That said if one person's plugin is of better quality or offers a stronger feature set with either the editor or the formatter I'd be in favor around collaborating towards a more 'official' sublime prettier plugin we can add to package control. Doesn't matter if it's based off of the one I started or not. Either way this is great lots of promise around this formatter.

**Comment by danreeves** [comment] 2017-01-11 09:54
@jlangston agreed, I'm up for discussion. This is the first Sublime plugin I've made so I couldn't tell you about best practices in the space.

I noticed yours bundles some JS files and requires an npm install inside the package. Personally, I'd rather have the package defer to a global (or local to the project) installation of `prettier`. 

Yours does have a few nice options though; autoformat, file extensions.

**Comment by scottwarren** [comment] 2017-01-12 07:39
Have added a link in #143

**Comment by jlangston** [comment] 2017-01-12 18:21
@danreeves We can defer to a global install or bundle it in the repo. Does your plugin support formatting just a selection vs an entire file?  If it's something you'd like to spearhead maintaining we can move with your repo and just add whatever features we feel are missing. Things like auto format aren't that hard to add. I think we just want it to be configurable and expose whatever options the formatter supports and be able to act on a selection or an entire file.   

Also @scottwarren thanks for adding a PR but I do think we should probably have the prettier README link to whichever plugin we collectively nominate to back and get that one into Package control and link to that page from the prettier README so it's an easier install for users.

**Comment by danreeves** [comment] 2017-01-12 19:10
@jlangston It doesn't support it yet but from what I've written so far it would be a pretty simple addition. I'm happy to get started on adding these features and maintain it.

**Comment by danreeves** [comment] 2017-01-17 23:40
Looks like @jonlabelle has already made a PR to packagecontrol.io, and his versions already supports using either a prepackaged or globally installed `prettier`, so maybe lets just move on with his.

**Comment by viankakrisna** [comment] 2017-01-25 15:30
![image](https://cloud.githubusercontent.com/assets/9636410/22296766/c78eeee2-e34d-11e6-92e6-e9cf8d14ca56.png)
Anybody having this issue on windows?  I'm using 0.11.0. Linux works fine

**Comment by danreeves** [comment] 2017-01-25 15:35
Hey @viankakrisna, if you're using the plugin linked from the readme you might get a better response from at its repo: https://github.com/jonlabelle/SublimeJsPrettier

You could also clarify the issue. Is it the extra/wrong indentation of the `mainWindow.on` arguments?

**Comment by viankakrisna** [comment] 2017-01-25 15:39
yeah, overall it's just a wacky formatting. I'm using the one from the package control. is it the same?

**Comment by viankakrisna** [comment] 2017-01-25 15:40
will post the issue on its repo, i think it's the same

**Comment by danreeves** [comment] 2017-01-25 15:42
@viankakrisna Yep, that's the one 👍 

@jlongster This issues was resolved by #318 so should be closed?

**Comment by viankakrisna** [comment] 2017-01-25 16:44
I think the issue is with 0.11.0, 0.0.10 works fine
https://github.com/jonlabelle/SublimeJsPrettier/issues/8#issuecomment-275153404
https://github.com/jonlabelle/SublimeJsPrettier/issues/9
Not really sure where the problem is

**Closed** 2017-01-25 16:54 UTC
Labels: Editor Support

**Comment by dusty** [comment] 2017-01-28 17:16
I am using an alternative solution for sublime.  Just thought I'd share, in case there are any other eslint users.

I use this eslint plugin, to pass prettier rules to eslint
https://github.com/not-an-aardvark/eslint-plugin-prettier

This this plugin to warn me on errors inside sublime
https://github.com/roadhump/SublimeLinter-eslint 

Then this package to simply autofix via eslint --fix
https://github.com/TheSavior/ESLint-Formatter

I like it because I can place the rules I want to pass to prettier in my eslint config file checked into git vs matching my rules in the jsPrettier user settings with my eslint config.

eg:
```
# .eslintrc.json
{
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": ["error", { "singleQuote": true , "bracketSpacing": false }]
  }
}
```

**Comment by slashwhatever** [comment] 2017-09-20 08:51
[This](http://slashwhatever.com/code/leveraging-prettier-eslint-sublime/) is how I handled it in Sublime

Similar to @dusty with a few minor concessions due to legacy code considerations.
