### ISSUE TITLE
Invalid parens around ternary expressions

### ISSUE THREAD

**Issue by umidbekkarimov** [jlongster/prettier#501] opened 2017-01-28 17:01 UTC
Try this code with width 34, 35, 36. At 35 prettier will add one extra bracket.

Input:

```js
const foo = {
  bar: props.bar ? props.bar : noop,
  baz: props.baz
}
```

Output:

```js
// At 34: good
const foo = {
  bar: (
    props.bar ? props.bar : noop
  ),
  baz: props.baz
};
```

```js
// At 35: bad
const foo = {
  bar: props.bar ? props.bar : noop
  ),
  baz: props.baz
};
```

```js
// At 36: good
const foo = {
  bar: props.bar ? props.bar : noop,
  baz: props.baz
};
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20foo%20%3D%20%7B%5Cn%20%20bar%3A%20props.bar%20%3F%20props.bar%20%3A%20noop%2C%5Cn%20%20baz%3A%20props.baz%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A35%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment] 2017-01-28 20:01
cc @rattrayalex, is this something you added for JSX?

**Comment by rattrayalex** [comment] 2017-01-28 20:08
Weird. 

I don't think so, but I can try to dig into it later today or tomorrow.

**Comment by vjeux** [comment] 2017-01-28 20:35
Actually, the parenthesis were introduced on purpose by @yamafaktory in https://github.com/jlongster/prettier/pull/314

I'll let him and @jlongster comment on whether this is something we want or not. Turning this into a Needs Discussion label instead of bug.

**Comment by vjeux** [comment] 2017-01-28 20:36
Ohhh, actually I misread the description. There is indeed a bug

At 35, it outputs the closing bracket but not the opening one, which is invalid JavaScript.

```js
const foo = {
  bar: props.bar ? props.bar : noop
  ),
  baz: props.baz
};
```

**Comment by rattrayalex** [comment] 2017-01-28 20:37
@vjeux I don't think this is about whether the parens are a good idea;take a look at the example output with width set to 35 😉

**Comment by rattrayalex** [comment] 2017-01-28 20:38
Ah great you beat me to it!

**Comment by vjeux** [comment] 2017-01-28 20:40
The issue is that the ifBreak("(") and ifBreak(")") are in two different groups that may not break at the same time.

**Comment by vjeux** [comment] 2017-01-28 20:46
@umidbekkarimov thanks for the great bug report and sorry I got confused! #502 is a fix for it :)

**Comment by umidbekkarimov** [comment] 2017-01-29 06:27
@vjeux oh, been bit sleepy (and lazy 😅) when create this issue.

**Comment by umidbekkarimov** [comment] 2017-01-29 06:30
@vjeux little bit of offtop, I got es6+jsx project with ~700 files and can produce this kind of edge case bugs :) so wait for more.

**Comment by vjeux** [comment] 2017-01-29 20:51
@umidbekkarimov hopefully you don't find more :) If you do, we'll fix them quickly!

**Closed** 2017-01-30 15:03 UTC
Labels: bug
