### ISSUE TITLE
Indentation of chained conditions in if statements is off 

### ISSUE THREAD

**Issue by hollandThomas** [jlongster/prettier#550] opened 2017-02-01 14:27 UTC
i.e.

```js
if (
  globalId.id === null ||
    globalId.id === undefined ||
    globalId.id === ''
) {
}
```

instead of

```js
if (
  globalId.id === null ||
  globalId.id === undefined ||
  globalId.id === ''
) {
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22if%20(%5Cn%20%20globalId.id%20%3D%3D%3D%20null%20%7C%7C%5Cn%20%20%20%20globalId.id%20%3D%3D%3D%20undefined%20%7C%7C%5Cn%20%20%20%20globalId.id%20%3D%3D%3D%20''%5Cn)%20%7B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A60%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment] 2017-02-01 15:00
Thanks for the report, I also think that it looks busted but @jlongster told me that it was by design. I'll let him comment on why it is that way :)

**Comment by yamafaktory** [comment] 2017-02-03 20:47
Same as #567.

**Comment by vjeux** [comment] 2017-02-03 20:48
Let's close this one and keep the discussion on #567, thanks @yamafaktory for the pointer!

**Closed by vjeux** 2017-02-03 20:48 UTC
Labels: Needs discussion
