### ISSUE TITLE
--tab-width 2 goes crazy with JSX

### ISSUE THREAD

**Issue by epeli** [jlongster/prettier#479] opened 2017-01-26 11:55 UTC
Input `test.js`:

```js
function hello() {
return (
<div>
<span>hello</span>
</div>
);
}
```

Without any options

    prettier test.js

it outputs:

![screen shot 2017-01-26 at 13 51 57](https://cloud.githubusercontent.com/assets/225712/22330392/afe986c2-e3ce-11e6-9e34-ed527194c95c.png)

but with

    prettier test.js  --tab-width 2

it outputs:

![screen shot 2017-01-26 at 13 51 42](https://cloud.githubusercontent.com/assets/225712/22330404/c1492d1e-e3ce-11e6-82fd-f0d4a0025827.png)

I was expecting the same output from both. 

Using version 0.11.0.

**Comment by timjacobi** [comment] 2017-01-26 16:28
Which operating system are you on? I can't reproduce on OSX 10.11.6

**Comment by vjeux** [comment] 2017-01-26 16:54
I also cannot reproduce it on OSX. And I'm not sure what could cause this. Maybe @rattrayalex you have an idea.

**Comment by rattrayalex** [comment] 2017-01-26 16:56
@epeli is it outputting tab characters or spaces? Can you copy/paste the raw inputs and outputs here or a gist?

**Comment by rattrayalex** [comment] 2017-01-26 16:58
Ahhh, @epeli are your line breaks CRLF (`\r\n`) ? 

I used a bunch of `\n`-specific regexes in the JSX processing code.

**Comment by jaysoffian** [comment] 2017-01-26 17:24
https://github.com/jlongster/prettier/pull/452 fixed this issue I believe.

**Comment by lydell** [comment] 2017-01-26 17:27
@jaysoffian Nope, that PR was all about fixing this the following :)

```
$ prettier test.js --tab-width 4
test.js: { ● Validation Error:

  Option "tabWidth" must be of type:
    number
  but instead received:
    string

  Example:
  {
    "tabWidth": 2
  }

  name: '',
  message: '\u001b[31m\u001b[1m\u001b[1m●\u001b[1m Validation Error\u001b[22m:\n\n  Option \u001b[1m"tabWidth"\u001b[22m must be of type:\n    \u001b[1m\u001b[32mnumber\u001b[31m\u001b[22m\n  but instead received:\n    \u001b[1m\u001b[31mstring\u001b[31m\u001b[22m\n\n  Example:\n  {\n    \u001b[1m"tabWidth"\u001b[22m: \u001b[1m2\u001b[22m\n  }\n\u001b[39m' }
```

**Comment by vjeux** [comment] 2017-01-26 17:58
It seems to be working fine with windows line endings.

```js
cat -e test.js
function hello() {^M$
return (^M$
<div>^M$
<span>hello</span>^M$
</div>^M$
);^M$
}^M$

./bin/prettier.js test.js --tab-width 2 | cat -e
function hello() {$
  return ($
    <div>$
      <span>hello</span>$
    </div>$
  );$
}$
```

**Comment by vjeux** [comment] 2017-01-28 16:27
Closing this for now until @epeli gives us more information.

**Closed by vjeux** 2017-01-28 16:27 UTC
Labels: Needs More Information

**Comment by epeli** [comment] 2017-02-14 13:09
Sorry for the delay but it seems that the issue is not present anymore in 0.17.0. Awesome tool, thanks!
